[package]
name = "Starlight"
version = "1.5.0"
description = "Among Us mod manager"
authors = [ "yanpla" ]
license = "MIT"
repository = "https://github.com/yanpla/Starlight"
edition = "2021"

[lib]
name = "starlight_lib"
crate-type = [
  "staticlib",
  "cdylib",
  "rlib"
]

[build-dependencies.tauri-build]
version = "2.4.1"
features = [ ]

[dependencies]
tauri-plugin-shell = "2.3.1"
tauri-plugin-notification = "2.3.1"
tauri-plugin-os = "2.3.1"
tauri-plugin-fs = "2"
tauri-plugin-store = "2.4.0"
serde_json = "1"
log = "0.4.28"
tauri-plugin-log = "2"
reqwest = { version = "0.12", default-features = false, features = [
  "blocking",
  "rustls-tls",
] }
zip = { version = "0.6.6", default-features = false, features = [ "deflate" ] }

[dependencies.tauri]
version = "2.8.5"
features = [
  "tray-icon",
  "unstable"
]

[dependencies.serde]
version = "1"
features = [ "derive" ]

[target.'cfg(windows)'.dependencies]
winreg = "0.55.0"
sysinfo = "0.37.0"
